---
apiVersion: v1
kind: Namespace
metadata:

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: go-app-lk
automountServiceAccountToken: false
  name: go-app-lk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    security-patch-uuid: "5747b56b-0897-40f1-ba53-8f26d31c433d"
  labels:
    app: go-app-lk
  name: go-app-lk
  namespace: go-app-lk
spec:
  selector:
    matchLabels:
      app: go-app-lk
  template:
    metadata:
      labels:
        app: go-app-lk
    spec:
securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: app-lk
          image: lkup77/test_vuln_go:4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: go-app-lk
              protocol: TCP
          securityContext:
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: go-app-lk
  namespace: go-app-lk
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: go-app-lk
  selector:
    app: go-app-lk
  sessionAffinity: None
  type: LoadBalancer
