---
apiVersion: v1
kind: Namespace
metadata:
  name: go-app-lk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app-lk
  name: go-app-lk
  annotations:
    security-patch-uuid: dfcb8336-2648-4fcb-ba13-2937bb5e2275
  namespace: go-app-lk
spec:
  selector:
    matchLabels:
      app: go-app-lk
  template:
    metadata:
      labels:
        app: go-app-lk
    spec:
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      automountServiceAccountToken: false
      containers:
        - name: app-lk
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
          image: lkup77/test_vuln_go:4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: go-app-lk
              protocol: TCP
          resources:
            requests:
              cpu: 250m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: go-app-lk
  namespace: go-app-lk
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: go-app-lk
  selector:
    app: go-app-lk
  sessionAffinity: None
  type: LoadBalancer
