---
apiVersion: v1
kind: Namespace
metadata:
  name: go-app-lk
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: go-app-lk
automountServiceAccountToken: false
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app-lk
  name: go-app-lk
  namespace: go-app-lk
  annotations:
    security-patch-uuid: "3e72e627-6ddf-443e-a12d-92a4f630e38d"
spec:
  selector:
    matchLabels:
      app: go-app-lk
  template:
    metadata:
      labels:
        app: go-app-lk
    spec:
      serviceAccountName: default
      securityContext:
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: app-lk
          image: lkup77/test_vuln_go:4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: go-app-lk
              protocol: TCP
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL
          resources:
            requests:
              cpu: 250m
              memory: 100Mi

---
apiVersion: v1
kind: Service
metadata:
  name: go-app-lk
  namespace: go-app-lk
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: go-app-lk
  selector:
    app: go-app-lk
  sessionAffinity: None
  type: LoadBalancer
