---
apiVersion: v1
kind: Namespace
metadata:
  name: go-app-lk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-app-lk
  name: go-app-lk
  namespace: go-app-lk
  annotations:
    security-patch-uuid: e4f3d353-a75d-4e82-97fb-0ee20519cb85
spec:
  selector:
    matchLabels:
      app: go-app-lk
  template:
    metadata:
      labels:
        app: go-app-lk
    spec:
      automountServiceAccountToken: false
securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        fsGroup: 472
        supplementalGroups:
          - 0
      containers:
        - name: app-lk
          image: lkup77/test_vuln_go:4
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
              name: go-app-lk
              protocol: TCP
resources:
            requests:
              cpu: 250m
              memory: 100Mi
          securityContext:
readOnlyRootFilesystem: true
            capabilities:
              drop:
                - ALL

---
apiVersion: v1
kind: Service
metadata:
  name: go-app-lk
  namespace: go-app-lk
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: go-app-lk
  selector:
    app: go-app-lk
  sessionAffinity: None
  type: LoadBalancer
